[project]
name = 'forastero'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.core]
path = 'contracts/core.clar'
clarity_version = 3
epoch = 3.0

[contracts.extension-trait]
path = 'contracts/extension-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.forastero-token]
path = 'contracts/forastero-token.clar'
clarity_version = 3
epoch = 3.0

[contracts.ownable-trait]
path = 'contracts/ownable-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.proposal-trait]
path = 'contracts/proposal-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.sip010-ft-trait]
path = 'contracts/sip010-ft-trait.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
